{
  "magisk": {
    "version": "𝙄𝘼𝙈𝘾𝙎𝙔𝙏 V23",
    "versionCode": "23000",
    "link": "https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@23.0/app-release.apk",
    "note": "https://raw.githubusercontent.com/ramenop/magiskramenop/main/stable.md"
  },
  "stub": {
    "versionCode": "21",
    "link": "https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@23.0/stub-release.apk"
  }
}
